/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import edd.Grafo;
import funciones.FuncionTXT;
import funciones.Validaciones;
import java.io.IOException;
import javax.swing.JOptionPane;



/**
 *
 * @author vickysaldivia
 */
public class Menu extends javax.swing.JFrame {
    public static Grafo GrafoSimulacion = new Grafo();
    FuncionTXT StringTXT = new FuncionTXT();
    /**
     * Creates new form Menu
     */
    public Menu() {
        
        initComponents();
        this.CargarGrafoPreexistente.setEnabled(true);
        setResizable(false);
        
        this.PantallaCiudades.setText(String.valueOf(GrafoSimulacion.getCiudades().getSize()));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        EliminarCiudad = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        MostrarGrafo = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        PantallaCiudades = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        NuevaSimulacion = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        CargarGrafoPreexistente = new javax.swing.JButton();
        Guardar = new javax.swing.JButton();
        AgregarCiudad3 = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        EliminarGrafoCargado = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Maku", 1, 14)); // NOI18N
        jLabel1.setText("Disponibles:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        EliminarCiudad.setText("Eliminar Ciudad");
        EliminarCiudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarCiudadActionPerformed(evt);
            }
        });
        jPanel1.add(EliminarCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, -1, -1));

        jLabel2.setFont(new java.awt.Font("Maku", 1, 36)); // NOI18N
        jLabel2.setText("MENÚ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, -1, -1));

        MostrarGrafo.setText("Mostrar Grafo");
        MostrarGrafo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MostrarGrafoActionPerformed(evt);
            }
        });
        jPanel1.add(MostrarGrafo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, 130, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 260, 20));

        PantallaCiudades.setFocusable(false);
        PantallaCiudades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PantallaCiudadesActionPerformed(evt);
            }
        });
        jPanel1.add(PantallaCiudades, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 40, -1));

        jLabel3.setFont(new java.awt.Font("Maku", 1, 24)); // NOI18N
        jLabel3.setText("CIUDADES");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        NuevaSimulacion.setText("Nueva Simulación");
        NuevaSimulacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NuevaSimulacionActionPerformed(evt);
            }
        });
        jPanel1.add(NuevaSimulacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 210, -1));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 260, 20));

        CargarGrafoPreexistente.setText("Cargar Grafo Preexistente");
        CargarGrafoPreexistente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CargarGrafoPreexistenteActionPerformed(evt);
            }
        });
        jPanel1.add(CargarGrafoPreexistente, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 250, -1));

        Guardar.setText("Guardar");
        Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarActionPerformed(evt);
            }
        });
        jPanel1.add(Guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 130, -1));

        AgregarCiudad3.setText("Agregar Ciudad");
        AgregarCiudad3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarCiudad3ActionPerformed(evt);
            }
        });
        jPanel1.add(AgregarCiudad3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 130, -1));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 260, 20));

        jButton1.setText("X");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(282, 10, 30, -1));

        EliminarGrafoCargado.setText("Eliminar Grafo Cargado");
        EliminarGrafoCargado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarGrafoCargadoActionPerformed(evt);
            }
        });
        jPanel1.add(EliminarGrafoCargado, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 365, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MostrarGrafoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MostrarGrafoActionPerformed
        // TODO add your handling code here:
        if(GrafoSimulacion.getCiudades().getSize() >=4){
            MostrarGrafoInterfaz VentanaGrafo = new MostrarGrafoInterfaz(); 
            this.setVisible(false);
            VentanaGrafo.setLocationRelativeTo(null);
            VentanaGrafo.setVisible(true);
        }
        else{
            JOptionPane.showMessageDialog(null, "\n"+"Necesita al menos 4 ciudades para mostrar el Grafo" + "\n\n" + "Ciudades actuales: " + GrafoSimulacion.getCiudades().getSize());
        }
        
    }//GEN-LAST:event_MostrarGrafoActionPerformed

    private void CargarGrafoPreexistenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CargarGrafoPreexistenteActionPerformed
        // TODO add your handling code here:
        if(GrafoSimulacion.getCiudades().isEmpty()){
            CargarGrafoInterfaz VentanaCargarGrafo = new CargarGrafoInterfaz();
            this.setVisible(false);
            VentanaCargarGrafo.setLocationRelativeTo(null);
            VentanaCargarGrafo.setVisible(true);
        }else{
             JOptionPane.showMessageDialog(null, "Ya hay un grafo en el sistema");
        }
    }//GEN-LAST:event_CargarGrafoPreexistenteActionPerformed

    private void AgregarCiudad3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarCiudad3ActionPerformed
        // TODO add your handling code here:
        int result = JOptionPane.showConfirmDialog(null, "Si no ha cargado un grafo preexistente," + "\n" + "no podrá hacerlo luego de ingresar a esta ventana." + "\n" + "¿Desea continuar?", "CONFIRMACIÓN",JOptionPane.YES_NO_OPTION);
        if(result == JOptionPane.YES_OPTION){
            AgregarCiudad VentanaAgregar = new AgregarCiudad(); 
            this.setVisible(false);
            VentanaAgregar.setLocationRelativeTo(null);
            VentanaAgregar.setVisible(true);
        }
    }//GEN-LAST:event_AgregarCiudad3ActionPerformed

    private void EliminarCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarCiudadActionPerformed
        // TODO add your handling code here:
        if(!GrafoSimulacion.getCiudades().isEmpty()){
            EliminarCiudad VentanaEliminar = new EliminarCiudad(); 
            this.setVisible(false);
            VentanaEliminar.setLocationRelativeTo(null);
            VentanaEliminar.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(null, "No hay ciudades disponibles");
        }
    }//GEN-LAST:event_EliminarCiudadActionPerformed

    private void NuevaSimulacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NuevaSimulacionActionPerformed
        // TODO add your handling code here:
        if(GrafoSimulacion.getCiudades().getSize() >=4){
            NuevaSimulacion VentanaSimulacion = new NuevaSimulacion(); 
            this.setVisible(false);
            VentanaSimulacion.setLocationRelativeTo(null);
            VentanaSimulacion.setVisible(true);
        }
        else{
            JOptionPane.showMessageDialog(null, "\n"+"Necesita al menos 4 ciudades para iniciar la Simulación" + "\n\n" + "Ciudades actuales: " + GrafoSimulacion.getCiudades().getSize());
        }
        
    }//GEN-LAST:event_NuevaSimulacionActionPerformed

    private void GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarActionPerformed
        // TODO add your handling code here:
        if(GrafoSimulacion.getCiudades().getSize() >=4){
            int confirmation = JOptionPane.showConfirmDialog(null, "Su simulación contiene " + GrafoSimulacion.getCiudades().getSize()+ " ciudades" + "\n" + "¿Desea guardar los cambios actuales? (No podrá agregar/eliminar más ciudades)", "CONFIRMACIÓN",JOptionPane.YES_NO_OPTION);
            if(confirmation == JOptionPane.YES_OPTION){
                    try {
                        StringTXT.StringTXT(GrafoSimulacion, "GrafoSimulacion.txt");
                        JOptionPane.showMessageDialog(null, "Guardado Exitoso.");
                        this.EliminarGrafoCargado.setEnabled(true);
                        this.NuevaSimulacion.setEnabled(true);
                        this.MostrarGrafo.setEnabled(true);
                    } catch (IOException ex) {
                        JOptionPane.showMessageDialog(null, "ERROR. Fallo al guardar el archivo");
                        
                    }
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "\n"+"Necesita al menos 4 ciudades para la Simulación" + "\n\n" + "Ciudades actuales: " + GrafoSimulacion.getCiudades().getSize());
        }
    }//GEN-LAST:event_GuardarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void PantallaCiudadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PantallaCiudadesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PantallaCiudadesActionPerformed

    private void EliminarGrafoCargadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarGrafoCargadoActionPerformed
        // TODO add your handling code here:
        if(GrafoSimulacion.getCiudades().getSize() > 0){
            int confirmation = JOptionPane.showConfirmDialog(null, "Su simulación contiene " + GrafoSimulacion.getCiudades().getSize()+ " ciudades" + "\n" +
                "¿Desea eliminar los datos actuales?", "CONFIRMACIÓN",JOptionPane.YES_NO_OPTION);
            if(confirmation == JOptionPane.YES_OPTION){
               StringTXT.eliminarArchivo("GrafoSimulacion.txt");
               GrafoSimulacion.emptyGrafo();
               JOptionPane.showMessageDialog(null, "Datos eliminados exitosamente");
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "\n"+"Simulación vacía" + "\n\n" + "Ciudades actuales: " + GrafoSimulacion.getCiudades().getSize());
        }
        
    }//GEN-LAST:event_EliminarGrafoCargadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarCiudad3;
    private javax.swing.JButton CargarGrafoPreexistente;
    private javax.swing.JButton EliminarCiudad;
    private javax.swing.JButton EliminarGrafoCargado;
    private javax.swing.JButton Guardar;
    private javax.swing.JButton MostrarGrafo;
    private javax.swing.JButton NuevaSimulacion;
    private javax.swing.JTextField PantallaCiudades;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    // End of variables declaration//GEN-END:variables
}
