/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import static GUI.Menu.GrafoSimulacion;
import edd.Ciudad;
import edd.ListaSimple;
import funciones.FuncionRellenarCombos;
import funciones.funcionAgregarCiudad;
import javax.swing.JOptionPane;

/**
 *
 * @author vickysaldivia
 */
public class AgregarCiudad extends javax.swing.JFrame {
    Menu VentanaMenu = new Menu();
    
    /**
     * Creates new form Agregar_Ciudad
     */
    FuncionRellenarCombos re = new FuncionRellenarCombos();
    ListaSimple<Ciudad> ciudadesAgregadas = new ListaSimple();
    funcionAgregarCiudad func = new funcionAgregarCiudad();
    public AgregarCiudad() {
        
        initComponents();
        setResizable(false);
        this.AgregarAristas.setEnabled(false);
        this.Guardar.setEnabled(false);
        this.ComboAristas.setEnabled(false);
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        NombreCiudad = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        ComboAristas = new javax.swing.JComboBox<>();
        AgregarCiudad = new javax.swing.JButton();
        Volver = new javax.swing.JButton();
        AgregarAristas = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        DistanciaTexto = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        Guardar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(241, 246, 240));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Thonburi", 1, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(83, 26, 11));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("AGREGAR CIUDAD");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 300, -1));

        jLabel1.setFont(new java.awt.Font("Thonburi", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(83, 26, 11));
        jLabel1.setText("DISTANCIA:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, -1, 40));

        NombreCiudad.setBackground(new java.awt.Color(255, 255, 255));
        NombreCiudad.setFont(new java.awt.Font("Helvetica", 1, 13)); // NOI18N
        NombreCiudad.setForeground(new java.awt.Color(83, 26, 11));
        NombreCiudad.setToolTipText("Solo se permiten dígitos (0-9)");
        NombreCiudad.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.black, java.awt.Color.white));
        NombreCiudad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                NombreCiudadMouseEntered(evt);
            }
        });
        NombreCiudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreCiudadActionPerformed(evt);
            }
        });
        NombreCiudad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NombreCiudadKeyTyped(evt);
            }
        });
        jPanel1.add(NombreCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 70, 30));

        jLabel3.setFont(new java.awt.Font("Thonburi", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(83, 26, 11));
        jLabel3.setText("NOMBRE (ORIGEN): ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 190, 30));

        ComboAristas.setBackground(new java.awt.Color(83, 26, 11));
        ComboAristas.setFont(new java.awt.Font("Thonburi", 0, 13)); // NOI18N
        ComboAristas.setForeground(new java.awt.Color(241, 246, 240));
        ComboAristas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboAristasActionPerformed(evt);
            }
        });
        jPanel1.add(ComboAristas, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 100, 30));

        AgregarCiudad.setBackground(new java.awt.Color(83, 26, 11));
        AgregarCiudad.setFont(new java.awt.Font("Thonburi", 0, 13)); // NOI18N
        AgregarCiudad.setText("Agregar Ciudad");
        AgregarCiudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarCiudadActionPerformed(evt);
            }
        });
        jPanel1.add(AgregarCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, -1, -1));

        Volver.setBackground(new java.awt.Color(83, 26, 11));
        Volver.setFont(new java.awt.Font("Thonburi", 0, 13)); // NOI18N
        Volver.setText("Volver");
        Volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverActionPerformed(evt);
            }
        });
        jPanel1.add(Volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 80, 30));

        AgregarAristas.setBackground(new java.awt.Color(83, 26, 11));
        AgregarAristas.setFont(new java.awt.Font("Thonburi", 0, 13)); // NOI18N
        AgregarAristas.setText("Agregar Arista");
        AgregarAristas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarAristasActionPerformed(evt);
            }
        });
        jPanel1.add(AgregarAristas, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 240, -1));

        jLabel4.setFont(new java.awt.Font("Thonburi", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(83, 26, 11));
        jLabel4.setText("DESTINO:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, 40));

        DistanciaTexto.setBackground(new java.awt.Color(255, 255, 255));
        DistanciaTexto.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        DistanciaTexto.setForeground(new java.awt.Color(83, 26, 11));
        DistanciaTexto.setToolTipText("Se permiten dígitos (0-9) y punto (.) para decimales.");
        DistanciaTexto.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.black, java.awt.Color.white));
        DistanciaTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DistanciaTextoActionPerformed(evt);
            }
        });
        DistanciaTexto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                DistanciaTextoKeyTyped(evt);
            }
        });
        jPanel1.add(DistanciaTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 160, 60, 30));

        jSeparator1.setBackground(new java.awt.Color(83, 26, 11));
        jSeparator1.setForeground(new java.awt.Color(83, 26, 11));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 400, 20));

        Guardar.setBackground(new java.awt.Color(83, 26, 11));
        Guardar.setFont(new java.awt.Font("Thonburi", 0, 13)); // NOI18N
        Guardar.setText("Guardar");
        Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarActionPerformed(evt);
            }
        });
        jPanel1.add(Guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, 90, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Hormigas4.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, -1, 290));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 280));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void AgregarCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarCiudadActionPerformed
        // TODO add your handling code here:
        
        if(GrafoSimulacion.getCiudades().getSize() < 20){
            String num = NombreCiudad.getText();
            int numCiudad = Integer.parseInt(num);
            Ciudad newCiudad =  new Ciudad(numCiudad);
            
            if(GrafoSimulacion.getCiudad(numCiudad) == null){
                GrafoSimulacion.addCiudad(newCiudad);
                this.ciudadesAgregadas.Append(newCiudad);
                ComboAristas.removeAllItems();
                re.RellenarCombos(GrafoSimulacion.CiudadesToLista(), ComboAristas);
                if(GrafoSimulacion.CiudadesToLista().length() >= 6){
                    this.AgregarAristas.setEnabled(true);
                    this.ComboAristas.setEnabled(true);
                    }
                else{
                    JOptionPane.showMessageDialog(null, "Debe agregar al menos 4 ciudades.");
                }
                }
            else{
                JOptionPane.showMessageDialog(null, "La ciudad ya se encuentra en la simulación.");
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Se ha alcanzado el máximo de ciudades (20).");
        }
        
    }//GEN-LAST:event_AgregarCiudadActionPerformed

    private void VolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverActionPerformed
        // TODO add your handling code here:
        String string = func.verificarAristas(ciudadesAgregadas);
        if(string == null){
            this.setVisible(false);
            VentanaMenu.setLocationRelativeTo(null);
            VentanaMenu.setVisible(true);
        }
        else{
            JOptionPane.showMessageDialog(null, "Todavía hay ciudades sin aristas." + string);
        }
    }//GEN-LAST:event_VolverActionPerformed

    private void AgregarAristasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarAristasActionPerformed
        // TODO add your handling code here:
        if(!"".equals(DistanciaTexto.getText())){
            int numCiudadOrigen = Integer.parseInt(NombreCiudad.getText());
            String ciudad = ComboAristas.getSelectedItem().toString();
            int numCiudadDestino = Integer.parseInt(ciudad);
            double distancia = Double.parseDouble(DistanciaTexto.getText());
            
            if(numCiudadOrigen != numCiudadDestino){
                if(GrafoSimulacion.getCiudad(numCiudadOrigen).buscarArista(numCiudadDestino) == null){
                    GrafoSimulacion.addArista(numCiudadOrigen, numCiudadDestino, distancia);
                    this.DistanciaTexto.setText("");
                    this.Guardar.setEnabled(true);
                    JOptionPane.showMessageDialog(null, "Aristas agregadas.\n" + GrafoSimulacion.stringCiudad(numCiudadOrigen));
                }
                else{
                    JOptionPane.showMessageDialog(null, "Ya existe una arista entre ambas ciudades seleccionadas.");
                }
            }
            else{
                JOptionPane.showMessageDialog(null, "La ciudad origen y destino NO pueden ser iguales");
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Necesita añadir un valor para la distancia.");
        }
    }//GEN-LAST:event_AgregarAristasActionPerformed

    private void NombreCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreCiudadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreCiudadActionPerformed

    private void DistanciaTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DistanciaTextoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DistanciaTextoActionPerformed

    private void GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarActionPerformed
        // TODO add your handling code here:
        this.NombreCiudad.setEditable(true);
        
        this.AgregarCiudad.setEnabled(true);
        this.AgregarAristas.setEnabled(false);
        this.Guardar.setEnabled(false);
        this.ComboAristas.setEnabled(false);
    }//GEN-LAST:event_GuardarActionPerformed

    private void ComboAristasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboAristasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboAristasActionPerformed

    
    private void NombreCiudadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NombreCiudadKeyTyped
        // TODO add your handling code here:
        int key = evt.getKeyChar();
        boolean numero = key >=48 && key <= 57;
        if(!numero){
            evt.consume();
        }
    }//GEN-LAST:event_NombreCiudadKeyTyped

    private void NombreCiudadMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NombreCiudadMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreCiudadMouseEntered

    private void DistanciaTextoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DistanciaTextoKeyTyped
        // TODO add your handling code here:
        int key = evt.getKeyChar();
        boolean numero = key == 46 || key >=48 && key <= 57;
        if(!numero){
            evt.consume();
        }
    }//GEN-LAST:event_DistanciaTextoKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarCiudad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarCiudad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarCiudad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarCiudad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarCiudad().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarAristas;
    private javax.swing.JButton AgregarCiudad;
    private javax.swing.JComboBox<String> ComboAristas;
    private javax.swing.JTextField DistanciaTexto;
    private javax.swing.JButton Guardar;
    private javax.swing.JTextField NombreCiudad;
    private javax.swing.JButton Volver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
