/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import edd.Grafo;
import edd.ListaSimple;
import funciones.FuncionTXT;
import funciones.MostrarGrafo;
import java.io.IOException;
import javax.swing.JOptionPane;


/**
 *
 * @author vickysaldivia
 */
public class Menu extends javax.swing.JFrame {
    public static Grafo GrafoSimulacion = new Grafo();
    FuncionTXT StringTXT = new FuncionTXT();
    
    
    /**
     * Creates new form Menu
     */
    public Menu() {
        
        initComponents();
        this.CargarGrafoPreexistente.setEnabled(true);
        setResizable(false);
        
        this.PantallaCiudades.setText(String.valueOf(GrafoSimulacion.getCiudades().getSize()));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        EliminarCiudad = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        MostrarGrafo = new javax.swing.JButton();
        PantallaCiudades = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        NuevaSimulacion = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        CargarGrafoPreexistente = new javax.swing.JButton();
        Guardar = new javax.swing.JButton();
        AgregarCiudad3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        EliminarGrafoCargado = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(241, 246, 240));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(83, 26, 11));
        jLabel1.setText("Disponibles:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 90, -1));

        EliminarCiudad.setBackground(new java.awt.Color(83, 26, 11));
        EliminarCiudad.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        EliminarCiudad.setForeground(new java.awt.Color(255, 255, 255));
        EliminarCiudad.setText("Eliminar Ciudad");
        EliminarCiudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarCiudadActionPerformed(evt);
            }
        });
        jPanel1.add(EliminarCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 130, -1));

        jLabel2.setBackground(new java.awt.Color(241, 246, 240));
        jLabel2.setFont(new java.awt.Font("Arial", 1, 50)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(83, 26, 11));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("MENÚ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 220, 70));

        MostrarGrafo.setBackground(new java.awt.Color(83, 26, 11));
        MostrarGrafo.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        MostrarGrafo.setForeground(new java.awt.Color(255, 255, 255));
        MostrarGrafo.setText("Mostrar Grafo");
        MostrarGrafo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MostrarGrafoActionPerformed(evt);
            }
        });
        jPanel1.add(MostrarGrafo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 280, -1));

        PantallaCiudades.setBackground(new java.awt.Color(218, 221, 217));
        PantallaCiudades.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        PantallaCiudades.setForeground(new java.awt.Color(83, 26, 11));
        PantallaCiudades.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        PantallaCiudades.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.black, java.awt.Color.white));
        PantallaCiudades.setFocusable(false);
        PantallaCiudades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PantallaCiudadesActionPerformed(evt);
            }
        });
        jPanel1.add(PantallaCiudades, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 40, 30));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(83, 26, 11));
        jLabel3.setText("CIUDADES");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 130, -1));

        NuevaSimulacion.setBackground(new java.awt.Color(83, 26, 11));
        NuevaSimulacion.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        NuevaSimulacion.setForeground(new java.awt.Color(255, 255, 255));
        NuevaSimulacion.setText("Nueva Simulación");
        NuevaSimulacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NuevaSimulacionActionPerformed(evt);
            }
        });
        jPanel1.add(NuevaSimulacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 280, -1));

        jSeparator2.setForeground(new java.awt.Color(83, 26, 11));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 280, 20));

        CargarGrafoPreexistente.setBackground(new java.awt.Color(83, 26, 11));
        CargarGrafoPreexistente.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        CargarGrafoPreexistente.setForeground(new java.awt.Color(255, 255, 255));
        CargarGrafoPreexistente.setText("Cargar Grafo Preexistente");
        CargarGrafoPreexistente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CargarGrafoPreexistenteActionPerformed(evt);
            }
        });
        jPanel1.add(CargarGrafoPreexistente, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 240, 30));

        Guardar.setBackground(new java.awt.Color(83, 26, 11));
        Guardar.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        Guardar.setForeground(new java.awt.Color(255, 255, 255));
        Guardar.setText("Guardar");
        Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarActionPerformed(evt);
            }
        });
        jPanel1.add(Guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 100, -1));

        AgregarCiudad3.setBackground(new java.awt.Color(83, 26, 11));
        AgregarCiudad3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        AgregarCiudad3.setForeground(new java.awt.Color(255, 255, 255));
        AgregarCiudad3.setText("Agregar Ciudad");
        AgregarCiudad3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarCiudad3ActionPerformed(evt);
            }
        });
        jPanel1.add(AgregarCiudad3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 130, -1));

        jButton1.setBackground(new java.awt.Color(83, 26, 11));
        jButton1.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("X");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 30, -1));

        jButton2.setBackground(new java.awt.Color(83, 26, 11));
        jButton2.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("↵");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, 30, -1));

        EliminarGrafoCargado.setBackground(new java.awt.Color(83, 26, 11));
        EliminarGrafoCargado.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        EliminarGrafoCargado.setForeground(new java.awt.Color(255, 255, 255));
        EliminarGrafoCargado.setText("Eliminar Grafo Cargado");
        EliminarGrafoCargado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarGrafoCargadoActionPerformed(evt);
            }
        });
        jPanel1.add(EliminarGrafoCargado, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, 180, -1));

        jSeparator4.setForeground(new java.awt.Color(83, 26, 11));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 280, 20));

        jSeparator5.setForeground(new java.awt.Color(83, 26, 11));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 280, 20));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Hormigas3.jpg"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Hormigas3.jpg"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/newwindow.jpg"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 40, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 361, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MostrarGrafoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MostrarGrafoActionPerformed
        // TODO add your handling code here:
        if(GrafoSimulacion.getCiudades().getSize() >=4){

            MostrarGrafo mostrar = new MostrarGrafo();
            mostrar.GrafoMostrar(GrafoSimulacion, new ListaSimple());
        }
        else{
            JOptionPane.showMessageDialog(null, "\n"+"Necesita al menos 4 ciudades para mostrar el Grafo" + "\n\n" + "Ciudades actuales: " + GrafoSimulacion.getCiudades().getSize());
        }
        
    }//GEN-LAST:event_MostrarGrafoActionPerformed

    private void CargarGrafoPreexistenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CargarGrafoPreexistenteActionPerformed
        // TODO add your handling code here:
        if(GrafoSimulacion.getCiudades().isEmpty()){
            CargarGrafoInterfaz VentanaCargarGrafo = new CargarGrafoInterfaz();
            this.setVisible(false);
            VentanaCargarGrafo.setLocationRelativeTo(null);
            VentanaCargarGrafo.setVisible(true);
        }else{
             JOptionPane.showMessageDialog(null, "Ya hay un grafo cargado en el sistema");
             int result = JOptionPane.showConfirmDialog(null, "Ya hay un grafo cargado en el sistema\n" + "¿Desea sustiuir la información existente?", "CONFIRMACIÓN", JOptionPane.YES_NO_OPTION);
             if(result  == JOptionPane.YES_OPTION){
                CargarGrafoInterfaz VentanaCargarGrafo = new CargarGrafoInterfaz();
                this.setVisible(false);
                VentanaCargarGrafo.setLocationRelativeTo(null);
                VentanaCargarGrafo.setVisible(true); 
             }
        }
    }//GEN-LAST:event_CargarGrafoPreexistenteActionPerformed

    private void AgregarCiudad3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarCiudad3ActionPerformed
        // TODO add your handling code here:
        AgregarCiudad VentanaAgregar = new AgregarCiudad(); 
        this.setVisible(false);
        VentanaAgregar.setLocationRelativeTo(null);
        VentanaAgregar.setVisible(true);
        
    }//GEN-LAST:event_AgregarCiudad3ActionPerformed

    private void EliminarCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarCiudadActionPerformed
        // TODO add your handling code here:
        if(!GrafoSimulacion.getCiudades().isEmpty()){
            EliminarCiudad VentanaEliminar = new EliminarCiudad(); 
            this.setVisible(false);
            VentanaEliminar.setLocationRelativeTo(null);
            VentanaEliminar.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(null, "No hay ciudades disponibles");
        }
    }//GEN-LAST:event_EliminarCiudadActionPerformed

    private void NuevaSimulacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NuevaSimulacionActionPerformed
        // TODO add your handling code here:
        if(GrafoSimulacion.getCiudades().getSize() >=4){
            NuevaSimulacion VentanaSimulacion = new NuevaSimulacion(); 
            this.setVisible(false);
            VentanaSimulacion.setLocationRelativeTo(null);
            VentanaSimulacion.setVisible(true);
        }
        else{
            JOptionPane.showMessageDialog(null, "\n"+"Necesita al menos 4 ciudades para iniciar la Simulación" + "\n\n" + "Ciudades actuales: " + GrafoSimulacion.getCiudades().getSize());
        }
        
    }//GEN-LAST:event_NuevaSimulacionActionPerformed

    private void GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarActionPerformed
        // TODO add your handling code here:
        if(GrafoSimulacion.getCiudades().getSize() >=4){
            int confirmation = JOptionPane.showConfirmDialog(null, "Su simulación contiene " + GrafoSimulacion.getCiudades().getSize()+ " ciudades" + "\n" + "¿Desea guardar los cambios actuales?", "CONFIRMACIÓN",JOptionPane.YES_NO_OPTION);
            if(confirmation == JOptionPane.YES_OPTION){
                    try {
                        StringTXT.String_TXT2(GrafoSimulacion.toString());
                        JOptionPane.showMessageDialog(null, "Guardado Exitoso.");
                        this.EliminarGrafoCargado.setEnabled(true);
                        this.NuevaSimulacion.setEnabled(true);
                        this.MostrarGrafo.setEnabled(true);
                    } catch (IOException ex) {
                        JOptionPane.showMessageDialog(null, "ERROR. Fallo al guardar el archivo");
                        
                    }
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "\n"+"Necesita al menos 4 ciudades para la Simulación" + "\n\n" + "Ciudades actuales: " + GrafoSimulacion.getCiudades().getSize());
        }
    }//GEN-LAST:event_GuardarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void PantallaCiudadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PantallaCiudadesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PantallaCiudadesActionPerformed

    private void EliminarGrafoCargadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarGrafoCargadoActionPerformed
        // TODO add your handling code here:
        if(GrafoSimulacion.getCiudades().getSize() > 0){
            int confirmation = JOptionPane.showConfirmDialog(null, "Su simulación contiene " + GrafoSimulacion.getCiudades().getSize()+ " ciudades" + "\n" +
                "¿Desea eliminar los datos actuales?", "CONFIRMACIÓN",JOptionPane.YES_NO_OPTION);
            if(confirmation == JOptionPane.YES_OPTION){
               StringTXT.eliminarArchivo();
               GrafoSimulacion.emptyGrafo();
               JOptionPane.showMessageDialog(null, "Datos eliminados exitosamente");
               this.PantallaCiudades.setText(String.valueOf(GrafoSimulacion.getCiudades().getSize()));
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "\n"+"Simulación vacía" + "\n\n" + "Ciudades actuales: " + GrafoSimulacion.getCiudades().getSize());
        }
        
    }//GEN-LAST:event_EliminarGrafoCargadoActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Bienvenido VentanaBienvenido = new Bienvenido();
        this.setVisible(false);
        VentanaBienvenido.setLocationRelativeTo(null);
        VentanaBienvenido.setVisible(true);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarCiudad3;
    private javax.swing.JButton CargarGrafoPreexistente;
    private javax.swing.JButton EliminarCiudad;
    private javax.swing.JButton EliminarGrafoCargado;
    private javax.swing.JButton Guardar;
    private javax.swing.JButton MostrarGrafo;
    private javax.swing.JButton NuevaSimulacion;
    private javax.swing.JTextField PantallaCiudades;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    // End of variables declaration//GEN-END:variables
}
